name: Deploy build to EKS

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

concurrency:
  group: "cd-deployment"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name eks-cluster \
            --region ${{ secrets.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          terraform -chdir=k8s init
          terraform -chdir=k8s apply -auto-approve
